### PR TITLE
Temporary fix to dependencies

### PR DESCRIPTION
**Pull request by moalamri**
@YogliB 
Is it ok to be included in the `optionalDependencies`? I didn't test it as I included them in the `devDependencies`

### CODE REVIEW

**Review by moalamri — COMMENTED** [review]
@YogliB

**Comment by YogliB** [comment]
first thing, thanks for contributing!
that said, I don't understand, why would we want to add these dependencies to our `package.json`?

FullCalendar has tons of plugins, it doesn't make sense to make them dependencies for this project...

**Comment by moalamri** [comment]
Hey @YogliB ,
Since we migrated to Vite, svelte-fullcalendar started to throw this error #805 in development environment.
We tried every solution possible, but couldn’t have it fixed.
So the only way is to add those packages, or let’s say the used packages, is by adding them into svelte-fullcalendar it self. If there’s any other way what could it be? Is there a way to dynamically or non-manually add dependencies to svelte-fullcalendar?

thank you..

**Comment by YogliB** [comment]
there's no way i know to dynamically add dependencies to a npm package...
can you make a reproduction repo for me to check out?

**Comment by moalamri** [comment]
Ok there will be a mini project to reproduce this by Monday
Thank you..

**Comment by themesbrand** [comment]
I have uploaded the code to the public repository for now so you can check the issue.
https://github.com/themesbrand/calendar-svelte-vite
Waiting for your update.
FYI: I will delete this repository later.

Thank you

**Comment by moalamri** [comment]
@themesbrand thanks for the demo. I cloned and it did reproduce the error. 
The maintainer don’t have notifications on due to using bots in this repo (they kinda annoying) so I’m gonna mentioned him. @YogliB 

As there’s no way of dynamically inject dependencies. If I may suggest? I think there could be four possible solutions:
- Have somehow a way to fix the issue (I couldn’t know how) 😞 
- Add the required dependencies (as in this commit)
- Make 2 different copies where one is core and the other has the extra dependencies (so you still have the main feature of being a lightweight wrapper)
- Add to docs a method to include the extra libraries by editing this library’s source (not recommended)

best option would be the first one, but could be time consuming to you? Because I found it pretty hard to debug since I didn’t try the source code itself.
I can give you a hint to this issue. It popped up after using Vite. And only shows up in development. So the final built production ready is ok and doesn’t show any error.
So it must be something related to how Vite build/merge/tree shake during development.

Thank you for your work of this library.

**Comment by themesbrand** [comment]
@YogliB Have you looked over the shared reproduction repo?

**Comment by YogliB** [comment]
> @YogliB Have you looked over the shared reproduction repo?

hey, I worked on that last night, and no matter what I tried, I didn't manage to make the FullCalendar component work in a SvelteKit project.

I changed the component, changed the project, but no combination got it to work, at all.

the only way it worked for me (and probably why my tests in this repo are working), was working with the FullCalendar library directly, without the component...

i think I will try next to maybe write an action for SvelteKit project and see if it works...

**Comment by moalamri** [comment]
@YogliB 
Thank you for putting your time in this.
I want to ask if you also had the same error on Sveltekit in production?

**Comment by YogliB** [comment]
> @YogliB Thank you for putting your time in this. I want to ask if you also had the same error on Sveltekit in production?

Didn't try, so i'll try and let you know 🙂

**Comment by YogliB** [comment]
Hey, y'all 👋
I just released a new beta version, and it would be great if you would read the updated README and try it out.

**Pull request closed without merging**
