### PR TITLE
Upgrade to fullcalendar 6

### PR DESCRIPTION
**Pull request by benmccann**
## Motivation

Closes https://github.com/YogliB/svelte-fullcalendar/issues/804

## Implementation

Upgrade to the latest version of fullcalendar

### CODE REVIEW

**Comment by YogliB** [comment]
just solve the conflicts and I'll merge and publish a new version

**Comment by YogliB** [comment]
and thanks!

**Comment by YogliB** [comment]
@all-contributors please add @benmccann for code

**Comment by benmccann** [comment]
thank you! resolved the merge conflicts!

**Review by YogliB — APPROVED** [review]

**Comment by Afrowave** [comment]
Hello @YogliB,  
  
Thank you for the good work and that you @benmccann for this particular issue. I was looking around [https://www.npmjs.com/package/svelte-fullcalendar](https://www.npmjs.com/package/svelte-fullcalendar) and found there is no update with this commit. Any news on this?

**Pull request merged**
